import sqlite3
conn = sqlite3.connect('database/attention.db')
c = conn.cursor()
row = c.execute("SELECT session_id, score, accuracy, level, time, correct, error, miss, total_target, total_step FROM game_raw_data WHERE session_id = 8").fetchone()
print(f'session_id={row[0]}')
print(f'score={row[5]}')
print(f'accuracy={row[6]}')
print(f'level={row[7]}')
print(f'time={row[8]}')
print(f'correct={row[9]}')
print(f'error={row[10]}')
print(f'miss={row[11]}')
print(f'total_target={row[12]}')
print(f'total_step={row[13]}')
conn.close()
