[uwsgi]
# %d 表示此配置文件所在目录（backend/）
#项目目录
chdir = %d

#指定项目application
wsgi-file = %dapp.py

#python 程序内用以启动的application 变量名
callable = app

# 进程个数
processes = 4

# 线程个数
threads = 2

#指定启动时的pid文件路径（用于停止服务和重启服务，请勿删除）
pidfile = %duwsgi.pid

# 指定ip及端口（部署时修改此处）
http = 0.0.0.0:5000
#socket = 0.0.0.0:5000

#启动uwsgi的用户名和用户组（部署时取消注释并修改）
;uid = www
;gid = www

#启用主进程
master = true

# 设置缓冲区大小
buffer-size = 32768

# 后台运行并输出日志（部署时取消注释）
;daemonize = /www/wwwlogs/python/backend/uwsgi.log

