AUTH_ERROR = 'AUTH_ERROR'
PERMISSION_DENIED = 'PERMISSION_DENIED'
NOT_FOUND = 'NOT_FOUND'
VALIDATION_ERROR = 'VALIDATION_ERROR'
DATABASE_ERROR = 'DATABASE_ERROR'
BAD_REQUEST = 'BAD_REQUEST'
INTERNAL_ERROR = 'INTERNAL_ERROR'
TOKEN_EXPIRED = 'TOKEN_EXPIRED'
TOKEN_INVALID = 'TOKEN_INVALID'
RESOURCE_NOT_FOUND = 'RESOURCE_NOT_FOUND'
USER_NOT_FOUND = 'USER_NOT_FOUND'
DUPLICATE_ENTRY = 'DUPLICATE_ENTRY'
RATE_LIMIT_EXCEEDED = 'RATE_LIMIT_EXCEEDED'

ERROR_MESSAGES = {
    AUTH_ERROR: '认证失败',
    PERMISSION_DENIED: '权限不足',
    NOT_FOUND: '资源不存在',
    VALIDATION_ERROR: '数据验证失败',
    DATABASE_ERROR: '数据库操作失败',
    BAD_REQUEST: '请求参数错误',
    INTERNAL_ERROR: '服务器内部错误',
    TOKEN_EXPIRED: 'Token已过期',
    TOKEN_INVALID: 'Token无效',
    RESOURCE_NOT_FOUND: '请求的资源不存在',
    USER_NOT_FOUND: '用户不存在',
    DUPLICATE_ENTRY: '数据已存在',
    RATE_LIMIT_EXCEEDED: '请求频率超限',
}

HTTP_STATUS_MAP = {
    AUTH_ERROR: 401,
    PERMISSION_DENIED: 403,
    NOT_FOUND: 404,
    VALIDATION_ERROR: 400,
    DATABASE_ERROR: 500,
    BAD_REQUEST: 400,
    INTERNAL_ERROR: 500,
    TOKEN_EXPIRED: 401,
    TOKEN_INVALID: 401,
    RESOURCE_NOT_FOUND: 404,
    USER_NOT_FOUND: 404,
    DUPLICATE_ENTRY: 409,
    RATE_LIMIT_EXCEEDED: 429,
}
